[tox]
envlist =
    py{310,311,312}-django{42,51,52}

[testenv]
commands =
    pytest
deps =
    pytest
    django42: django==4.2.*
    django51: django==5.1.*
    django52: django==5.2.*
setenv =
    PYTHONPATH = {toxinidir}

[flake8]
max-line-length = 120
max-complexity = 10
